[project]
name = 'interdimensional-practice-portal'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.dimensional-stability-monitor]
path = 'contracts/dimensional-stability-monitor.clar'
clarity_version = 3
epoch = 3.1

[contracts.temporal-distortion-generator]
path = 'contracts/temporal-distortion-generator.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
